### ISSUE TITLE
Tiered Admin Permissions

### ISSUE THREAD

**Issue by g33kcub** [digibeardev/UrsaMU#17]
I would like to see tiered control for admins. Maybe Mirror RhostMUSH, where the tier above inherits all the abilities of that below. And that you can only affect items/players/etc with a tier lower than yours. 

Immortal = Can control everything, can also alter server settings from within the game.
Wizard = Can control everything, but the immortal level stuff. Can alter some settings from with the game.
Royal/Admin = Can control everything below them.
Architect = Primary Builder staff bit, has access to builder powers.
Staff = The first full staff rank. Has standard staff powers and control anything below them.
Judge = Has some limited staff access to powers, but cannot control anything. 
Citizen/Player = Your base character.
Guest = Your base guest character with all the restrictions.

**Comment by lcanady** [comment]
Good stuff.  I've been working on flags recently, figuring out what to represent.  I'll use this list. :)

**Comment by lcanady** [comment]
Closing this for now.  The permissions have been set, they just need further testing.
